spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ktb_community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useSSL=false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  jwt:
    issuer: restapi-subject
    access-exp-ms: 600000 # 10분
    refresh-exp-ms: 1209600000 # 2주

  jackson:
    time-zone: Asia/Seoul
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
file:
#  upload-dir: uploads
#  base-url: http://localhost:8080/uploads
  allowed-ext: png,jpg,jpeg,gif,webp
  max-size-mb: 5

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    persistAuthorization: true
    groups-order: desc
    operations-sorter: method
    tags-sorter: alpha
    csrf:
      enabled: false
    with-credentials: true

custom:
  cookie:
    secure: true
    same-site: None
    path: /
    max-age-days: 14
